### ISSUE TITLE
Ошибка в типе значения параметра по умолчанию

### ISSUE THREAD

**Issue by khaale** [tamtam-chat/tamtam-bot-api-schema#16]
Параметр `count ` метода `GET /chats/{chatId}/members` имеет тип _integer_, но дефолтное значение указано как строка. Это приводит к поломке некоторых OpenApi парсеров, например Microsoft.OpenApi.Readers.
```
        - name: count
          description: Count
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: '20'
```
https://github.com/tamtam-chat/tamtam-bot-api-schema/blob/80675f95864fee47a2db8b8f3986ee8929a031e3/schema.yaml#L773
